### ISSUE TITLE
Include CSS in autoDependency

### ISSUE THREAD

**Issue by slowe** [open-innovations/oi-lume-utils#1]
As well as processing JS files, it could also process CSS files.

**Comment by slowe** [comment]
@gilesdring Does my fix work? I just tested for ".css" in the dependency. If that doesn't match it behaves as it did before. I'd like to be able to include CSS files as dependencies in oi-lume-charts.

**Comment by slowe** [comment]
@gilesdring Just bumping this. My potential fix is on the "Add CSS" branch. It would be very helpful to be able to include CSS for oi-lume-charts to make sure the leaflet.css gets included properly (especially for embeddable versions of examples).

**Comment by slowe** [comment]
@gilesdring I don't really know how to test my changes so I haven't merged the branch. I also don't know if something special needs to be done for `oi-lume-charts` to have access to updates of this.

**Comment by gilesdring** [comment]
I shall take a look

**Comment by gilesdring** [comment]
I've made a couple of tweaks that I'm just testing on the oi-lume-charts example site.

I've updated the import in `_config.js` to point to the file on my local repo.

```js
import autoDependency from '../../oi-lume-utils/processors/auto-dependency.ts';
```

I can see that this 

```html
<div data-dependencies="not-a-css.css">Hello</div>
```

Adds this to the `head`

```html
<link href="not-a-css.css" rel="stylesheet" data-auto-dependency="true">
```

Looks like that's done for now... I'll merge and cut a new release, then add to the example site.
